[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[staticAssets]
strip = false

[start]
cmd = "nginx -g 'daemon off;'"
